version: '3.8'

services:
  front:
    image: nginx:stable-alpine
    container_name: ${CONTAINER_GROUP}-front
    restart: "on-failure"
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: ${CONTAINER_GROUP}-server
    restart: "on-failure"
    expose:
      - "4000"
    volumes:
      - ./src:/var/www/html
